# Add here module-specific custom log4j.properties configuration

# Base package logger
log4j.logger.migrator.name=org.alfresco.extension
log4j.logger.migrator.level=debug

# Detailed exporter/importer flow
log4j.logger.migrator.exporter-component.name=org.alfresco.extension.repo.exporter.ExporterComponent
log4j.logger.migrator.exporter-component.level=debug

log4j.logger.migrator.importer-component.name=org.alfresco.extension.repo.importer.ImporterComponent
log4j.logger.migrator.importer-component.level=debug

# Action executers
log4j.logger.migrator.exporter-action.name=org.alfresco.extension.repo.action.executer.ExporterActionExecuter
log4j.logger.migrator.exporter-action.level=debug

log4j.logger.migrator.importer-action.name=org.alfresco.extension.repo.action.executer.ImporterActionExecuter
log4j.logger.migrator.importer-action.level=debug
